newsapi_key = "4669d31f641040ada4b63df917478b8d"
finnhub_api_key = "d1fejkpr01qig3h1a9cgd1fejkpr01qig3h1a9d0"
aws_access_key_id = AKIASVLKCO2NYVNEIN5K
aws_secret_access_key = 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
region = us-east-1
output = json
