newsapi_key = "4669d31f641040ada4b63df917478b8d"
finnhub_api_key = "d1fejkpr01qig3h1a9cgd1fejkpr01qig3h1a9d0"
aws_access_key_id = "AKIASVLKCO2N5BN2LINZ"
aws_secret_access_key = "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"
region = "us-east-1"
output = "json"